apiVersion: logger.logger.com/v1
kind: Logger
metadata:
  labels:
    app.kubernetes.io/name: logger-controller
    app.kubernetes.io/managed-by: kustomize
  name: logger-sample
spec:
  scope:
    type: namespace
    namespace: default
  resources:
    - pods
    - deployments
    - replicasets
    - nodes
  trigger: 30s
